apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meusite
  name: meusite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meusite
  template:
    metadata:
      labels:
        app: meusite
    spec:
      containers:
        - env:
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka:29092
            - name: KAFKA_CLUSTERS_0_NAME
              value: "main"
          image: hashicorp/http-echo
          args:
            - -text=banana
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: meusite
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5678
          resources:
            limits:
              cpu: 250m
              memory: 32Mi
            requests:
              cpu: 150m
              memory: 16Mi
      hostname: meusite
      restartPolicy: Always
           