apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meusite
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /meusite
        pathType: Prefix
        backend:
          service:
            name: meusite
            port:
              number: 5678