apiVersion: v1
kind: Service
metadata:
  name: meusite
  namespace: default
  labels:
    app: meusite
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 5678
      port: 5678
  selector:
    app: meusite