apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: meusite
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: meusite
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50